/* ============================================================
   VisionQuantech Business Suite — Legal Notice Draft Tool
   apps/legal-notice-draft-tool/app.js

   Pure functions first (no DOM) — tested under node.
   Builds a TEMPLATE-based legal notice for payment default.
   This is a DRAFTING aid only — never a filed-ready document.
   Prominent disclaimer: get a lawyer to review before sending.
   Stateless: nothing is persisted.
   ============================================================ */
(function () {
  'use strict';

  /* ---------------- pure computations ---------------- */

  var MAX_TEXT = 500;
  var MAX_AMOUNT = 1000000000;

  function validateText(v, label, maxLen) {
    var s = String(v == null ? '' : v).trim();
    if (!s) return { ok: false, error: label + ' is required.' };
    if (s.length > (maxLen || MAX_TEXT)) return { ok: false, error: label + ' is too long (max ' + (maxLen || MAX_TEXT) + ' characters).' };
    return { ok: true, value: s };
  }

  function validateAmount(v) {
    var n = Number(v);
    if (!isFinite(n)) return { ok: false, error: 'Enter a valid overdue amount.' };
    if (n <= 0) return { ok: false, error: 'Overdue amount must be greater than zero.' };
    if (n > MAX_AMOUNT) return { ok: false, error: 'Amount looks too large.' };
    return { ok: true, value: n };
  }

  function validateDate(v, label) {
    var s = String(v == null ? '' : v).trim();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(s)) return { ok: false, error: label + ' must be a valid date (YYYY-MM-DD).' };
    var d = new Date(s + 'T00:00:00');
    if (isNaN(d.getTime()) || d.toISOString().slice(0, 10) !== s)
      return { ok: false, error: label + ' is not a real calendar date.' };
    return { ok: true, value: s };
  }

  function daysBetween(a, b) {
    var da = new Date(a + 'T00:00:00'), db = new Date(b + 'T00:00:00');
    return Math.round((db - da) / 86400000);
  }

  /** Validate all fields; returns {ok, error} or {ok:true, value:data}. */
  function validateNotice(data) {
    var d = data || {};
    var sender = validateText(d.senderName, 'Sender (your) name', 200);
    if (!sender.ok) return sender;
    var recip = validateText(d.recipientName, "Recipient's name", 200);
    if (!recip.ok) return recip;
    var amt = validateAmount(d.amount);
    if (!amt.ok) return amt;
    var inv = validateText(d.invoiceNo, 'Invoice / bill number', 100);
    if (!inv.ok) return inv;
    var invDate = validateDate(d.invoiceDate, 'Invoice date');
    if (!invDate.ok) return invDate;
    var dueDate = validateDate(d.dueDate, 'Due date');
    if (!dueDate.ok) return dueDate;
    if (daysBetween(invDate.value, dueDate.value) < 0)
      return { ok: false, error: 'Due date cannot be before the invoice date.' };
    var days = Number(d.demandDays);
    if (!isFinite(days) || Math.floor(days) !== days || days < 3 || days > 60)
      return { ok: false, error: 'Demand period must be 3 to 60 days.' };
    var addr = validateText(d.senderAddress, 'Sender address', 500);
    if (!addr.ok) return addr;
    var raddr = validateText(d.recipientAddress, 'Recipient address', 500);
    if (!raddr.ok) return raddr;
    var today = validateDate(d.dateOfNotice, 'Notice date');
    if (!today.ok) return today;
    return {
      ok: true,
      value: {
        senderName: sender.value, senderAddress: addr.value,
        recipientName: recip.value, recipientAddress: raddr.value,
        invoiceNo: inv.value, amount: amt.value,
        invoiceDate: invDate.value, dueDate: dueDate.value,
        demandDays: days, dateOfNotice: today.value
      }
    };
  }

  function fmtINR(n) {
    var v = Math.round((+n || 0) * 100) / 100;
    return '\u20B9' + Math.abs(v).toLocaleString('en-IN', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
  }
  function inWords(n) {
    // Simple Indian-system words for common ranges (helper, not a full converter)
    return 'Rupees ' + fmtINR(n);
  }

  var DISCLAIMER = 'DRAFT ONLY — NOT LEGAL ADVICE. This is a template generated by a tool. It is NOT a filed-ready legal document. Have a qualified lawyer review and finalise it before sending or using it.';

  /** Build the notice text from VALIDATED data. */
  function buildNotice(v) {
    var overdueDays = daysBetween(v.dueDate, v.dateOfNotice);
    var L = [];
    L.push('LEGAL NOTICE (DRAFT — SUBJECT TO LAWYER REVIEW)');
    L.push('');
    L.push('Date: ' + v.dateOfNotice);
    L.push('');
    L.push('From: ' + v.senderName);
    L.push(v.senderAddress);
    L.push('');
    L.push('To: ' + v.recipientName);
    L.push(v.recipientAddress);
    L.push('');
    L.push('Re: Demand for payment of overdue amount of ' + fmtINR(v.amount) + ' against Invoice No. ' + v.invoiceNo + ' dated ' + v.invoiceDate + '.');
    L.push('');
    L.push('Dear Sir/Madam,');
    L.push('');
    L.push('1. Under instructions from my client, ' + v.senderName + ', I address this notice to you as follows.');
    L.push('2. That my client raised Invoice No. ' + v.invoiceNo + ' dated ' + v.invoiceDate + ' for ' + fmtINR(v.amount) + ' (' + inWords(v.amount) + ' only), which fell due for payment on ' + v.dueDate + '.');
    L.push('3. That despite the expiry of the due date (' + Math.max(overdueDays, 0) + ' day(s) overdue as of this notice), the said amount remains unpaid, and repeated reminders have not yielded payment.');
    L.push('4. That my client hereby calls upon you to pay the sum of ' + fmtINR(v.amount) + ' within ' + v.demandDays + ' days of receipt of this notice, failing which my client shall be constrained to initiate appropriate legal proceedings for recovery, at your risk as to costs and consequences.');
    L.push('5. This notice is issued without prejudice to any other rights and remedies available to my client.');
    L.push('');
    L.push('Yours faithfully,');
    L.push('(Through counsel)');
    L.push(v.senderName);
    L.push('');
    L.push('---');
    L.push(DISCLAIMER);
    return L.join('\n');
  }

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  var API = {
    DISCLAIMER: DISCLAIMER,
    validateNotice: validateNotice, buildNotice: buildNotice,
    daysBetween: daysBetween, validateAmount: validateAmount,
    validateDate: validateDate, validateText: validateText,
    fmtINR: fmtINR, esc: esc
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = API;
    return;
  }

  /* ---------------- browser UI ---------------- */
  if (typeof window === 'undefined' || typeof document === 'undefined') return;

  var SLUG = 'legal-notice-draft-tool';
  var FREE_LIMIT = 20;

  function $(id) { return document.getElementById(id); }
  function msg(t, ok) {
    var el = $('l-msg');
    el.textContent = t;
    el.className = 'vq-hint ' + (ok === true ? 'msg-ok' : ok === false ? 'msg-err' : 'vq-hint');
  }
  function todayStr() { return new Date().toISOString().slice(0, 10); }

  function renderResult(text) {
    var card = $('l-result-card');
    card.hidden = false;
    $('l-result').innerHTML =
      '<p class="legal-warn"><strong>⚠ ' + esc(DISCLAIMER) + '</strong></p>' +
      '<pre class="notice">' + esc(text) + '</pre>' +
      '<button id="l-copy" class="vq-btn" type="button">Copy draft</button> ' +
      '<button id="l-print" class="vq-btn vq-btn-ghost" type="button">Print</button>';
    $('l-copy').addEventListener('click', function () {
      if (navigator.clipboard) navigator.clipboard.writeText(text);
      msg('Draft copied. Remember: get a lawyer to review before sending.', true);
    });
    $('l-print').addEventListener('click', function () { window.print(); });
    card.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }

  function init() {
    Ads.render($('ad-top'), 'legal-notice-draft-tool-top', 'leaderboard');
    Ads.render($('ad-bottom'), 'legal-notice-draft-tool-bottom', 'leaderboard');
    SEO.faq([
      { q: 'What should a legal notice for payment default contain?', a: 'Parties, invoice details, amount, due date, days overdue, a clear demand with a deadline (usually 15–30 days), and a warning of further action. This tool drafts that structure — a lawyer must review it.' },
      { q: 'भुगतान न मिलने पर लीगल नोटिस कैसे बनाएं?', a: 'पार्टियों के नाम-पते, इनवॉइस डिटेल, बकाया रकम, ड्यू डेट और स्पष्ट मांग के साथ। यह टूल ड्राफ्ट बनाता है — भेजने से पहले वकील से रिव्यू ज़रूर कराएं।' },
      { q: 'Is a legal notice mandatory before filing a case?', a: 'Not always, but it strengthens recovery suits and often triggers payment. Your lawyer will advise based on the dispute type.' },
      { q: 'Can I send this draft as-is?', a: 'No. This is a template, not a filed-ready legal document. Wrong facts or wording can hurt your case — get a lawyer to review.' },
      { q: 'How long should the demand period be?', a: '15 days is the common default; this tool allows 3–60 days. Your lawyer may adjust it.' },
      { q: 'Is this legal advice?', a: 'No. This tool does not give legal advice. Consult a qualified lawyer for your situation.' }
    ]);
    $('l-date').value = todayStr();
    $('l-calc').addEventListener('click', function () {
      var gate = Freemium.check(SLUG, FREE_LIMIT);
      if (!gate.allowed) { Freemium.renderUpsell($('l-gate'), SLUG, FREE_LIMIT); $('l-gate').scrollIntoView({ behavior: 'smooth' }); return; }
      var r = validateNotice({
        senderName: $('l-sender').value, senderAddress: $('l-sender-addr').value,
        recipientName: $('l-recipient').value, recipientAddress: $('l-recipient-addr').value,
        invoiceNo: $('l-inv').value, amount: $('l-amount').value,
        invoiceDate: $('l-inv-date').value, dueDate: $('l-due-date').value,
        demandDays: $('l-days').value, dateOfNotice: $('l-date').value
      });
      if (!r.ok) { msg(r.error, false); $('l-result-card').hidden = true; return; }
      msg('', null);
      renderResult(buildNotice(r.value));
    });
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
