/* ============================================================
   VisionQuantech Business Suite — License Activation Engine (DEMO)
   apps/license-activation-engine/app.js

   *** DEMO ONLY — NOT A REAL LICENSING SYSTEM ***
   Demonstrates the key format used for the suite's Pro licensing:
   signed keys with an embedded checksum. Real licensing runs
   server-side; never ship client-generated keys for real products.

   Key format: VQ1-<PROD4>-<BODY8>-<CHECK4>
   CHECK4 = (sum of char codes of PROD4+BODY8, weighted) mod 36^4,
   rendered base-36, uppercase, 4 chars.

   Pure functions first (no DOM) — tested under node.
   ============================================================ */
(function () {
  'use strict';

  var PREFIX = 'VQ1';
  var CHARSET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no 0/O/1/I
  var PROD_LEN = 4, BODY_LEN = 8, CHECK_LEN = 4;

  function randBody(n) {
    var s = '';
    for (var i = 0; i < n; i++) s += CHARSET[Math.floor(Math.random() * CHARSET.length)];
    return s;
  }

  /** Weighted char-code sum checksum, base-36 padded to 4 chars. */
  function checksum(payload) {
    var sum = 0;
    for (var i = 0; i < payload.length; i++) {
      sum = (sum + payload.charCodeAt(i) * (i + 1) * 31) % 1679616; // 36^4
    }
    var out = sum.toString(36).toUpperCase();
    while (out.length < CHECK_LEN) out = '0' + out;
    return out;
  }

  function validProduct(code) {
    return typeof code === 'string' && /^[A-Z0-9]{4}$/.test(code.trim().toUpperCase());
  }

  function generateKey(productCode, owner) {
    productCode = String(productCode == null ? '' : productCode).trim().toUpperCase();
    if (!validProduct(productCode)) return { ok: false, error: 'Product code must be exactly 4 letters/digits (e.g. VQPS).' };
    owner = String(owner == null ? '' : owner).trim().slice(0, 60);
    var body = randBody(BODY_LEN);
    var payload = productCode + body;
    var key = PREFIX + '-' + productCode + '-' + body + '-' + checksum(payload);
    return { ok: true, key: key, product: productCode, owner: owner, note: 'DEMO key — not for production licensing.' };
  }

  function validateKey(key) {
    var raw = String(key == null ? '' : key).trim().toUpperCase().replace(/\s+/g, '');
    if (!raw) return { ok: true, valid: false, reason: 'Enter a license key.' };
    var parts = raw.split('-');
    if (parts.length !== 4) return { ok: true, valid: false, reason: 'Key must have 4 dash-separated groups (VQ1-PROD-BODY-CHECK).' };
    if (parts[0] !== PREFIX) return { ok: true, valid: false, reason: 'Bad prefix — expected "' + PREFIX + '".' };
    if (!validProduct(parts[1])) return { ok: true, valid: false, reason: 'Bad product code — expected 4 letters/digits.' };
    var bodyRe = new RegExp('^[' + CHARSET + ']{' + BODY_LEN + '}$');
    if (!bodyRe.test(parts[2])) return { ok: true, valid: false, reason: 'Bad key body — characters outside the allowed set.' };
    if (!/^[0-9A-Z]{4}$/.test(parts[3])) return { ok: true, valid: false, reason: 'Bad checksum group — expected 4 alphanumerics.' };
    var expected = checksum(parts[1] + parts[2]);
    if (parts[3] !== expected) return { ok: true, valid: false, reason: 'Checksum mismatch — key was typed wrong or tampered with.' };
    return { ok: true, valid: true, product: parts[1], reason: 'Signature valid (demo check only).' };
  }

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  var API = {
    PREFIX: PREFIX, CHECK_LEN: CHECK_LEN,
    generateKey: generateKey, validateKey: validateKey,
    checksum: checksum, esc: esc
  };

  if (typeof module !== 'undefined' && module.exports) { module.exports = API; return; }
  if (typeof window === 'undefined' || typeof document === 'undefined') return;

  /* ---------------- browser UI ---------------- */
  var SLUG = 'license-activation-engine';
  var FREE_LIMIT = 20;

  function $(id) { return document.getElementById(id); }
  function msg(t, ok) {
    var el = $('l-msg');
    el.textContent = t;
    el.className = 'vq-hint ' + (ok === true ? 'msg-ok' : ok === false ? 'msg-err' : '');
  }

  function init() {
    Ads.render($('ad-top'), 'license-activation-engine-top', 'leaderboard');
    Ads.render($('ad-bottom'), 'license-activation-engine-bottom', 'leaderboard');
    SEO.faq([
      { q: 'Is this a real license server?', a: 'No — this is a labelled demo showing the key format (VQ1-PROD-BODY-CHECK) and checksum validation. Real Pro licensing runs server-side; never rely on client-generated keys.' },
      { q: 'लाइसेंस की कैसे बनती है?', a: 'डेमो फॉर्मैट: VQ1-प्रोडक्टकोड-8 अक्षर-4 अक्षर चेकसम। चेकसम प्रोडक्ट कोड और बॉडी से बनता है, ताकि टाइपिंग गलती या छेड़छाड़ पकड़ी जा सके।' },
      { q: 'What does the checksum prove?', a: 'Only that the key was generated by this tool and not mistyped or edited afterwards. It is not encryption and not copy protection.' },
      { q: 'Can I use these keys for my own product?', a: 'Not as shown. Use a server-side licensing system (e.g. signed tokens verified on your backend). This demo exists to show customers the format.' }
    ]);

    $('l-gen').addEventListener('click', function () {
      var gate = Freemium.check(SLUG, FREE_LIMIT);
      if (!gate.allowed) { Freemium.renderUpsell($('l-gate'), SLUG, FREE_LIMIT); $('l-gate').scrollIntoView({ behavior: 'smooth' }); return; }
      var r = generateKey($('l-prod').value, $('l-owner').value);
      if (!r.ok) { msg(r.error, false); return; }
      $('l-out').hidden = false;
      $('l-out').innerHTML =
        '<p class="vq-hint">Demo key for product <strong>' + esc(r.product) + '</strong>' +
        (r.owner ? ' · licensed to <strong>' + esc(r.owner) + '</strong>' : '') + '</p>' +
        '<p class="key">' + esc(r.key) + '</p>' +
        '<p class="vq-hint demo-note">DEMO ONLY — not a real license. Do not use for production software.</p>';
      msg('', null);
    });

    $('l-val').addEventListener('click', function () {
      var gate = Freemium.check(SLUG, FREE_LIMIT);
      if (!gate.allowed) { Freemium.renderUpsell($('l-gate'), SLUG, FREE_LIMIT); $('l-gate').scrollIntoView({ behavior: 'smooth' }); return; }
      var r = validateKey($('l-key').value);
      $('l-out').hidden = false;
      $('l-out').innerHTML = r.valid
        ? '<p class="msg-ok">VALID demo key — product ' + esc(r.product) + '. ' + esc(r.reason) + '</p>'
        : '<p class="msg-err">INVALID — ' + esc(r.reason) + '</p>';
      msg('', null);
    });
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
